name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: ElrondNetwork/elrond-actions/.github/workflows/contracts.yml@v1
    with:
      rust-toolchain: nightly-2022-04-05
      vmtools-version: v1.4.48
      extra-build-args: --ignore-eei-checks --cargo-target-dir=/home/runner/work/elrond-wasm-rs/elrond-wasm-rs/target
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
